### PR TITLE
v0.15.4

### PR DESCRIPTION
**Pull request by rustybird**

### CODE REVIEW

**Comment by rustybird** [comment]
Bumped to v0.15.2 @fepitre

**Comment by rustybird** [comment]
Looks like some unrelated CI failures, let's see if I'm whitelisted to retry them:

**Comment by fepitre** [comment]
I'm waiting because I need to troubleshoot build infrastructure issues and it's in progress.

**Comment by rustybird** [comment]
PipelineRetryFailed

**Comment by rustybird** [comment]
@fepitre Oh sure

**Comment by fepitre** [comment]
> PipelineRetryFailed

Let me add you in the authorized list.

**Comment by rustybird** [comment]
PipelineRetryFailed

**Comment by rustybird** [comment]
Thanks for merging @fepitre. Looks like the build didn't pick up the new version though?

**Comment by fepitre** [comment]
> Thanks for merging @fepitre. Looks like the build didn't pick up the new version though?

It should be good. This is because I merged it and then tagged it after pushing.

**Comment by fepitre** [comment]
In fact I don't see it in the repo. Once again an issue happened. I need to check.

**Comment by rustybird** [comment]
Would it be feasible to refresh the checkout manually and kick off another build? @fepitre

There are so many problems with the old v0.15.0 that I'm like :grimacing: this is what people are getting (and will still be getting during the required stabilization period)

**Comment by rustybird** [comment]
ping @fepitre

**Comment by rustybird** [comment]
ping @fepitre

**Pull request merged**
