### PR TITLE
v0.15.5

### PR DESCRIPTION
**Pull request by rustybird**
Fingers crossed that qubes-builder really picks up the new version...

### CODE REVIEW

**Comment by rustybird** [comment]
PipelineRetryFailed

**Comment by rustybird** [comment]
Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64

**Comment by rustybird** [comment]
PipelineRetryFailed

**Comment by rustybird** [comment]
PipelineRetryFailed

**Comment by rustybird** [comment]
PipelineRetryFailed

**Comment by fepitre** [comment]
I'll merge it and allow failures for CentOS Stream 8

**Comment by rustybird** [comment]
Thanks for merging, can you also build it though? ;)

**Comment by rustybird** [comment]
Yay, thank you!

**Pull request merged**
