### PR TITLE
v0.13.0-2

### PR DESCRIPTION
**Pull request by rustybird**
This adds `BuildRequires: make` for fc34 compatibility.

@fepitre can you switch to `--ff` merges? The current workflow (where PRs are required by policy to be fast-forwardable, but then they're actually merged `--no-ff`) is a bit awkward because it means that the upstream repo has to pick up the empty merge commit from QubesOS-contrib downstream.

### CODE REVIEW

**Comment by fepitre** [comment]
@rustybird I'll adapt, indeed I do have --no-ff in my git alias.

**Comment by rustybird** [comment]
Was the additional version bump commit in QubesOS-contrib intended? I thought you might push just your tag.

**Comment by fepitre** [comment]
There is an issue with Debian orig archive: it used the same version and not release in its archive name pattern: https://github.com/QubesOS-contrib/build-logs/blob/master/build-debian1/log_2021-05-10_11-42-17#L280 else indeed that would have been sufficient. In general, we don't bump release for "internal" Qubes component because we generate source archive based on the content including changelog.

**Comment by rustybird** [comment]
Oh I see, thanks.

**Pull request merged**
