### PR TITLE
v0.16.0

### PR DESCRIPTION
**Pull request by rustybird**

### CODE REVIEW

**Comment by rustybird** [comment]
ping @fepitre

**Comment by fepitre** [comment]
Sorry, I missed the original PR notification.

**Comment by rustybird** [comment]
Thanks, can you trigger the build please?

**Comment by fepitre** [comment]
There is a build infra issue that can be solved only this evening.

**Comment by fepitre** [comment]
https://github.com/QubesOS/qubes-issues/issues/8325

**Pull request merged**
